"""
Generates schema/data_dictionary.md from the live Cloud SQL database.

Functions:
  load_private_skiplist()       — loads local exclusions
  build_contents(schemas)       — builds linked schema and relation navigation
  dump_data_dictionary()  — connects to the DB, queries all table/column metadata
                            and comments, writes data_dictionary.md

Includes both tables (relkind='r') and views (relkind='v'). A view is described by its comment
and columns, not its SQL: the definitions live in the database.
"""

import os
import sys
import psycopg2


# Queries every user-defined table and view across all schemas, with table and column comments.
QUERY = """
SELECT
    n.nspname                          AS schema,
    c.relname                          AS relation_name,
    c.relkind                          AS relkind,
    obj_description(c.oid, 'pg_class') AS table_comment,
    a.attnum                           AS column_num,
    a.attname                          AS column_name,
    pg_catalog.format_type(a.atttypid, a.atttypmod) AS data_type,
    NOT a.attnotnull                   AS nullable,
    pg_get_expr(d.adbin, d.adrelid)    AS column_default,
    col_description(c.oid, a.attnum)   AS column_comment
FROM
    pg_catalog.pg_class     c
    JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
    JOIN pg_catalog.pg_attribute a ON a.attrelid = c.oid
    LEFT JOIN pg_catalog.pg_attrdef d ON d.adrelid = c.oid AND d.adnum = a.attnum
WHERE
    c.relkind IN ('r', 'v')
    AND n.nspname NOT IN ('pg_catalog', 'information_schema', 'pg_toast')
    AND a.attnum > 0
    AND NOT a.attisdropped
ORDER BY
    n.nspname, c.relkind DESC, c.relname, a.attnum
"""

_PRIVATE_SKIPLIST_FILE = os.path.join(os.path.dirname(__file__), "private_relations.txt")


# Loads local relation exclusions; returns an empty set when none are configured.
def load_private_skiplist() -> set[str]:
    skip: set[str] = set()
    if not os.path.exists(_PRIVATE_SKIPLIST_FILE):
        return skip

    with open(_PRIVATE_SKIPLIST_FILE) as f:
        for line in f:
            name = line.split("#", 1)[0].strip()
            if name:
                skip.add(name)
    return skip


# Builds a compact table of contents using the anchors generated by GitHub Markdown headings.
# Receives the grouped schema metadata and returns Markdown lines for the published dictionary.
def build_contents(schemas: dict[str, dict[str, dict]]) -> list[str]:
    lines = [
        "\n## Contents\n",
        "\n| Schema | Relations |\n",
        "|--------|-----------|\n",
    ]

    for schema_name, relations in sorted(schemas.items()):
        schema_link = f"[`{schema_name}`](#schema-{schema_name})"
        relation_links = []
        for relation_name, meta in sorted(relations.items()):
            kind = "view" if meta["relkind"] == "v" else "table"
            anchor = f"{kind}-{schema_name}{relation_name}"
            relation_links.append(f"[`{relation_name}`](#{anchor})")
        lines.append(f"| {schema_link} | {' · '.join(relation_links)} |\n")

    return lines


# Connects using DATABASE_URL from environment, writes data_dictionary.md.
def dump_data_dictionary():
    database_url = os.environ.get("DATABASE_URL", "").strip()
    if not database_url:
        print("ERROR: DATABASE_URL not set", file=sys.stderr)
        sys.exit(1)

    conn = psycopg2.connect(database_url)
    cur = conn.cursor()

    cur.execute(QUERY)
    rows = cur.fetchall()

    conn.close()

    # Groups relations by schema and relation name, preserving relkind.
    skip = load_private_skiplist()
    skipped: set[str] = set()
    schemas: dict[str, dict[str, dict]] = {}
    for (schema, rel_name, relkind, table_comment, _, col_name,
         data_type, nullable, col_default, col_comment) in rows:
        if f"{schema}.{rel_name}" in skip:
            skipped.add(f"{schema}.{rel_name}")
            continue
        schemas.setdefault(schema, {})
        schemas[schema].setdefault(rel_name, {"comment": table_comment, "relkind": relkind, "columns": []})
        schemas[schema][rel_name]["columns"].append({
            "name": col_name,
            "type": data_type,
            "nullable": nullable,
            "default": col_default,
            "comment": col_comment,
        })

    lines = ["# Data Dictionary\n",
             "_Auto-generated. Do not edit by hand. Run `python schema/dump_data_dictionary.py` to refresh._\n"]
    lines.extend(build_contents(schemas))

    table_count = 0
    view_count = 0

    for schema_name, relations in sorted(schemas.items()):
        lines.append(f"\n## Schema: `{schema_name}`\n")
        for rel_name, meta in sorted(relations.items()):
            is_view = meta["relkind"] == "v"
            kind_label = "View" if is_view else "Table"
            lines.append(f"\n### {kind_label}: `{schema_name}.{rel_name}`\n")
            if meta["comment"]:
                lines.append(f"{meta['comment']}\n")
            if is_view:
                view_count += 1
            else:
                table_count += 1
            lines.append("\n| Column | Type | Nullable | Default | Notes |\n")
            lines.append("|--------|------|----------|---------|-------|\n")
            for col in meta["columns"]:
                nullable_str = "yes" if col["nullable"] else "no"
                default_str = (col["default"] or "").replace("|", "\\|").replace("\n", " ")
                comment_str = (col["comment"] or "").replace("|", "\\|").replace("\n", " ")
                lines.append(
                    f"| `{col['name']}` | `{col['type']}` | {nullable_str} "
                    f"| {default_str} | {comment_str} |\n"
                )

    out_path = os.path.join(os.path.dirname(__file__), "data_dictionary.md")
    with open(out_path, "w") as f:
        f.writelines(lines)

    print(f"Written: {out_path}")
    print(f"  {len(schemas)} schemas, {table_count} tables, {view_count} views")
    if skipped:
        print(f"  excluded {len(skipped)} relation(s): {', '.join(sorted(skipped))}")


if __name__ == "__main__":
    dump_data_dictionary()
